agent: Set required pymssql version to 2.1.5
Using pymssql v2.2.0 or later results in the following error message:
ImportError: /tmp/_MEISNYzdG/pymssql/_pymssql.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned